rosdistro: 'melodic

  '
roslaunch:
  uris: {host_ubuntu__34469: 'http://ubuntu:34469/'}
rosversion: '1.14.11

  '
run_id: 28ebb0f6-1c8f-11ec-9d60-001c42882a4f
turtlesim: {background_b: 255, background_g: 86, background_r: 69}
